
services:
  backend:
    build:
      context: ./Practica Backend
    env_file:
      - ./Practica Backend/.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./Practica Backend:/app
    networks:
      - bitacora-net

  frontend:
    build:
      context: ./Practica Frontend
    env_file:
      - ./Practica Frontend/.env.production
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - bitacora-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Example
      MYSQL_DATABASE: bitacora_infor
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - bitacora-net

volumes:
  db_data:

networks:
  bitacora-net:
